Content:
    thm:
        root_dir: ${ROOT_DIR}/doc/content
    thm_test:
        root_dir: ${ROOT_DIR}/test/doc/content
    framework:
        root_dir: ${MOOSE_DIR}/framework/doc/content
    modules:
        root_dir: ${MOOSE_DIR}/modules/doc/content
        content:
            - application_usage/command_line_usage.md
            - media/**
    fluid_properties:
        root_dir: ${MOOSE_DIR}/modules/fluid_properties/doc/content
    misc:
        root_dir: ${MOOSE_DIR}/modules/misc/doc/content
    heat_conduction:
        root_dir: ${MOOSE_DIR}/modules/heat_conduction/doc/content
        external: True
    ray_tracing:
        root_dir: ${MOOSE_DIR}/modules/ray_tracing/doc/content
    rdg:
        root_dir: ${MOOSE_DIR}/modules/rdg/doc/content
Renderer:
    type: MooseDocs.base.MaterializeRenderer
Extensions:
    MooseDocs.extensions.navigation:
        name: THM
        repo: https://hpcgitlab.hpc.inl.gov/idaholab/thm
        home: https://hpcsc.hpc.inl.gov/ssl/THM/site/
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        allow-test-objects: true
        unregister:
            framework: !include ${MOOSE_DIR}/framework/doc/unregister.yml
            thm:
                AddComponentAction: Components/*/*
                Component: Components/*/*
        remove:
            framework: !include ${MOOSE_DIR}/framework/doc/remove.yml
            heat_conduction:
                - /ThermalContact
            thm:
                - /Modules
            fluid_properties_test_app:
                - /Materials/MultiComponentFluidPropertiesMaterialPT
                - /AuxKernels/TwoPhaseAverageDensityAux
        alias:
            /FluidProperties: /Modules/FluidProperties
            /FluidProperties/AddFluidPropertiesAction: /Modules/FluidProperties/AddFluidPropertiesAction
            /FluidProperties/BrineFluidProperties: /Modules/FluidProperties/BrineFluidProperties
            /FluidProperties/CO2FluidProperties: /Modules/FluidProperties/CO2FluidProperties
            /FluidProperties/FlibeFluidProperties: /Modules/FluidProperties/FlibeFluidProperties
            /FluidProperties/FlinakFluidProperties: /Modules/FluidProperties/FlinakFluidProperties
            /FluidProperties/GeneralVaporMixtureFluidProperties: /Modules/FluidProperties/GeneralVaporMixtureFluidProperties
            /FluidProperties/HeliumFluidProperties: /Modules/FluidProperties/HeliumFluidProperties
            /FluidProperties/IdealGasFluidProperties: /Modules/FluidProperties/IdealGasFluidProperties
            /FluidProperties/IdealGasFluidPropertiesPT: /Modules/FluidProperties/IdealGasFluidPropertiesPT
            /FluidProperties/MethaneFluidProperties: /Modules/FluidProperties/MethaneFluidProperties
            /FluidProperties/NaClFluidProperties: /Modules/FluidProperties/NaClFluidProperties
            /FluidProperties/NitrogenFluidProperties: /Modules/FluidProperties/NitrogenFluidProperties
            /FluidProperties/HydrogenFluidProperties: /Modules/FluidProperties/HydrogenFluidProperties
            /FluidProperties/SodiumSaturationFluidProperties: /Modules/FluidProperties/SodiumSaturationFluidProperties
            /FluidProperties/SimpleFluidProperties: /Modules/FluidProperties/SimpleFluidProperties
            /FluidProperties/SodiumProperties: /Modules/FluidProperties/SodiumProperties
            /FluidProperties/StiffenedGasFluidProperties: /Modules/FluidProperties/StiffenedGasFluidProperties
            /FluidProperties/StiffenedGasTwoPhaseFluidProperties: /Modules/FluidProperties/StiffenedGasTwoPhaseFluidProperties
            /FluidProperties/TabulatedFluidProperties: /Modules/FluidProperties/TabulatedFluidProperties
            /FluidProperties/TwoPhaseFluidPropertiesIndependent: /Modules/FluidProperties/TwoPhaseFluidPropertiesIndependent
            /FluidProperties/Water97FluidProperties: /Modules/FluidProperties/Water97FluidProperties
            /FluidProperties/IdealRealGasMixtureFluidProperties: /Modules/FluidProperties/IdealRealGasMixtureFluidProperties
            /FluidProperties/LinearTestTwoPhaseFluidProperties: /Modules/FluidProperties/LinearTestTwoPhaseFluidProperties
        includes:
            - ${MOOSE_DIR}/framework/include
            - ${MOOSE_DIR}/modules/fluid_properties/include
            - ${MOOSE_DIR}/modules/heat_conduction/include
            - ${MOOSE_DIR}/modules/misc/include
            - include
            - test/include
    MooseDocs.extensions.common:
        shortcuts:
            framework: !include ${MOOSE_DIR}/framework/doc/globals.yml
            thm:
                Components: systems/Components/index.md
    MooseDocs.extensions.acronym:
        acronyms: !include ${MOOSE_DIR}/framework/doc/acronyms.yml
    MooseDocs.extensions.bibtex:
        duplicate_warning: false
    MooseDocs.extensions.katex:
        macros: !include ${ROOT_DIR}/doc/latex_macros.yml
    MooseDocs.extensions.template:
        active: true
    MooseDocs.extensions.sqa:
        active: true
        reports: !include ${ROOT_DIR}/doc/sqa_reports.yml
        categories:
            thm: !include ${ROOT_DIR}/doc/sqa_thm.yml
            framework: !include ${MOOSE_DIR}/framework/doc/sqa_framework.yml
            fluid_properties: !include ${MOOSE_DIR}/modules/fluid_properties/doc/sqa_fluid_properties.yml
            misc: !include ${MOOSE_DIR}/modules/misc/doc/sqa_misc.yml
            heat_conduction: !include ${MOOSE_DIR}/modules/heat_conduction/doc/sqa_heat_conduction.yml
            ray_tracing: !include ${MOOSE_DIR}/modules/ray_tracing/doc/sqa_ray_tracing.yml
            rdg: !include ${MOOSE_DIR}/modules/rdg/doc/sqa_rdg.yml
        repos:
            default: https://gitlab.software.inl.gov/idaholab/thm
            relap-7: https://hpcgitlab.hpc.inl.gov/idaholab/relap-7
