Content:
    - framework/doc/content
    - modules/heat_transfer/doc/content
    - modules/ray_tracing/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer

Extensions:
    MooseDocs.extensions.navigation:
        name: MOOSE Heat Transfer Module
        repo: https://github.com/idaholab/moose
        home: /modules/heat_transfer/index.md
    MooseDocs.extensions.appsyntax:
        executable: ${MOOSE_DIR}/modules/heat_transfer
        remove:
            framework: !include framework/doc/remove.yml
        unregister:
            framework: !include framework/doc/unregister.yml
        includes:
            - framework/include
            - modules/heat_transfer/include
            - modules/ray_tracing/include
    MooseDocs.extensions.common:
        shortcuts: !include framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms: !include framework/doc/acronyms.yml
    MooseDocs.extensions.template:
        active: True
    MooseDocs.extensions.sqa:
        active: True
        reports: !include modules/heat_transfer/doc/sqa_reports.yml
        categories:
            framework: !include framework/doc/sqa_framework.yml
            heat_transfer: !include modules/heat_transfer/doc/sqa_heat_transfer.yml
            ray_tracing: !include modules/ray_tracing/doc/sqa_ray_tracing.yml
