[tool.black]
target-version = ['py310', 'py311', 'py312', 'py313']
required-version = '25.1.0'
include = '''
(
  ^\/python\/moosecontrol\/.*.py$ |
  ^\/python\/moosepy\/.*.py$ |
  ^\/python\/moosefmu\/.*.py$ |
  ^\/python\/TestHarness\/resultsstore\/.*.py$ |
  ^\/python\/TestHarness\/resultssummary\/.*.py$ |
  ^\/python\/TestHarness/tests/resultsstore\/.*.py$ |
  ^\/python\/TestHarness/tests/resultssummary\/.*.py$ |
  ^\/test\/tests\/controls\/moose_fmu\/.*.py$
)
'''

[tool.ruff]
include = [
  "python/moosecontrol/**/*.py",
  "python/moosepy/**/*.py",
  "python/TestHarness/resultsstore/**/*.py",
  "python/TestHarness/resultssummary/**/*.py",
  "python/TestHarness/tests/resultsstore/**/*.py",
  "python/TestHarness/tests/resultssummary/**/*.py"
]
exclude = ["python/moosecontrol/requests_unixsocket/*.py"]

[tool.ruff.lint]
# Enable pycodestyle (E) and Pyflakes (F) codes by default.
# D - NumPy docstring rules
# I - Sorting imports
# N801 - Class name should use CapWords convention
# SIM - code simplification rules
# TID - tidy imports
select = ["D", "E", "F", "I", "N801", "SIM", "TID"]
ignore = ["D203", "D212"]
