repo: https://github.com/idaholab/moose/blob/master
doxygen: http://mooseframework.com/docs/doxygen/modules/
details: docs/details
prefix: systems/modules/phase_field
links:
    Tests:
      - tests
    Examples:
      - examples
