black:
  - black 26.1.0

clang_format:
  - clang-format 19

clang_tools:
  - clang-tools 19

ruff:
  - ruff 0.15.1

### If you change these versions also update conda/mpi/meta.yaml
### and conda/wasp/conda_build_config.yaml
moose_python:
  - python 3.14
  - python 3.13
  - python 3.12
  - python 3.11
  - python 3.10
