## Dependencies are listed in descending order.
## Any changes made will require additional changes to any item above that.

moose_libmesh:
  - 2021.09.15 build_0

moose_petsc:
  - 3.15.1 build_2

SHORT_VTK_NAME:
  - 6.3

vtk_version:
  - 6.3.0

moose_libmesh_vtk:
  - 6.3.0 build_7

moose_mpich:
  - 3.3.2 build_7

#### MOOSE_TOOLS stuff (order is important, must match python version order)
python:
  - 3.9
  - 3.8
  - 3.7
  - 3.6

vtk:
  - 9.0.1 no_osmesa_py39h3dd132e_102 # [osx]
  - 9.0.1 no_osmesa_py38h523a0c9_102 # [osx]
  - 9.0.1 no_osmesa_py37hc0470e1_102 # [osx]
  - 9.0.1 no_osmesa_py36hc362858_102 # [osx]
  - 9.0.3 no_osmesa_py39h801044d_100 # [linux]
  - 9.0.3 no_osmesa_py38h3850a3d_100 # [linux]
  - 9.0.3 no_osmesa_py37h7b56ff3_100 # [linux]
  - 9.0.3 no_osmesa_py36hfa3a401_100 # [linux]

numpy:
  - 1.21.0 py39h7eed0ac_0      # [osx]
  - 1.21.0 py38had91d27_0      # [osx]
  - 1.21.0 py37h84c02c4_0      # [osx]
  - 1.19.5 py36h08dc641_1      # [osx]
  - 1.21.0 py39hdbf815f_0      # [linux]
  - 1.21.0 py38h9894fe3_0      # [linux]
  - 1.21.0 py37h038b26d_0      # [linux]
  - 1.19.5 py36h2aa4a07_1      # [linux]

pyqt:
  - 5.12.3 py39h6e9494a_7      # [osx]
  - 5.12.3 py38h50d1736_7      # [osx]
  - 5.12.3 py37hf985489_7      # [osx]
  - 5.12.3 py36h79c6626_7      # [osx]
  - 5.12.3 py39hf3d152e_7      # [linux]
  - 5.12.3 py38h578d9bd_7      # [linux]
  - 5.12.3 py37h89c1867_7      # [linux]
  - 5.12.3 py36h5fab9bb_7      # [linux]

matplotlib:
  - 3.3.3 py39h6e9494a_0       # [osx]
  - 3.3.3 py38h50d1736_0       # [osx]
  - 3.3.3 py37hf985489_0       # [osx]
  - 3.3.3 py36h79c6626_0       # [osx]
  - 3.4.2 py39hf3d152e_0       # [linux]
  - 3.4.2 py38h578d9bd_0       # [linux]
  - 3.4.2 py37h89c1867_0       # [linux]
  - 3.3.4 py36h5fab9bb_0       # [linux]

pandas:
  - 1.2.1 py39h089d6f7_0       # [osx]
  - 1.2.1 py38he9f00de_0       # [osx]
  - 1.2.1 py37h010c265_0       # [osx]
  - 1.1.5 py36h2be6da3_0       # [osx]
  - 1.3.0 py39hde0f152_0       # [linux]
  - 1.3.0 py38h1abd341_0       # [linux]
  - 1.3.0 py37h219a48f_0       # [linux]
  - 1.1.5 py36h284efc9_0       # [linux]

pyyaml:
  - 5.4.1 py39hcbf5805_0       # [osx]
  - 5.4.1 py38h5406a74_0       # [osx]
  - 5.4.1 py37hf967b71_0       # [osx]
  - 5.4.1 py36h20b66c6_0       # [osx]
  - 5.4.1 py39h3811e60_0       # [linux]
  - 5.4.1 py38h497a2fe_0       # [linux]
  - 5.4.1 py37h5e8e339_0       # [linux]
  - 5.4.1 py36h8f6f2f9_0       # [linux]

pybtex:
  - 0.24.0 py39h6e9494a_0      # [osx]
  - 0.24.0 py38h50d1736_0      # [osx]
  - 0.24.0 py37hf985489_0      # [osx]
  - 0.24.0 py36h79c6626_0      # [osx]
  - 0.24.0 py39hf3d152e_0      # [linux]
  - 0.24.0 py38h578d9bd_0      # [linux]
  - 0.24.0 py37h89c1867_0      # [linux]
  - 0.24.0 py36h5fab9bb_0      # [linux]

mock:
  - 4.0.3 py39h6e9494a_1       # [osx]
  - 4.0.3 py38h50d1736_1       # [osx]
  - 4.0.3 py37hf985489_1       # [osx]
  - 4.0.3 py36h79c6626_1       # [osx]
  - 4.0.3 py39hf3d152e_1       # [linux]
  - 4.0.3 py38h578d9bd_1       # [linux]
  - 4.0.3 py37h89c1867_1       # [linux]
  - 4.0.3 py36h5fab9bb_1       # [linux]

lxml:
  - 4.6.3 py39hf41e7f8_0       # [osx]
  - 4.6.3 py38h6ea4786_0       # [osx]
  - 4.6.3 py37h250624f_0       # [osx]
  - 4.6.3 py36habcf893_0       # [osx]
  - 4.6.3 py39h107f48f_0       # [linux]
  - 4.6.3 py38hf1fe3a4_0       # [linux]
  - 4.6.3 py37h77fd288_0       # [linux]
  - 4.6.3 py36h04a5ba7_0       # [linux]

scikit_image:
  - 0.18.1 py39h089d6f7_0      # [osx]
  - 0.18.1 py38he9f00de_0      # [osx]
  - 0.18.1 py37h010c265_0      # [osx]
  - 0.17.2 py36h2be6da3_4      # [osx]
  - 0.18.2 py39hde0f152_0      # [linux]
  - 0.18.2 py38h1abd341_0      # [linux]
  - 0.18.2 py37h219a48f_0      # [linux]
  - 0.17.2 py36h284efc9_4      # [linux]

beautifulsoup4:
  - 4.9.3 pyhb0f4dca_0         # [linux]
  - 4.9.3 pyhb0f4dca_0         # [osx]

pylatexenc:
  - 2.10 pyhd8ed1ab_0          # [linux]
  - 2.10 pyhd8ed1ab_0          # [osx]

jinja2:
  - 3.0.1 pyhd8ed1ab_0         # [linux]
  - 3.0.1 pyhd8ed1ab_0         # [osx]

mako:
  - 1.1.4 pyh44b312d_0         # [linux]
  - 1.1.4 pyh44b312d_0         # [osx]

livereload:
  - 2.6.3 pyh9f0ad1d_0         # [linux]
  - 2.6.3 pyh9f0ad1d_0         # [osx]

yaml:
  - 0.2.5 h516909a_0           # [linux]
  - 0.2.5 haf1e3a3_0           # [osx]

zip_keys:
  - python
  - vtk
  - numpy
  - pyqt
  - matplotlib
  - pandas
  - pyyaml
  - pybtex
  - mock
  - lxml
  - scikit_image

#### Changes to the following require extensive testing
libllvm:
  - 11.0.0 hf85e3d2_0

libclang:
  - 11.0.0 default_h9e6edd0_2

compilerrt:
  - 11.0.0 h01488ec_2

compilerrtosx:
  - 11.0.0 hd3c4e95_2

clangxx:
  - 11.0.0 default_h9e6edd0_2

clangosx:
  - 11.0.0 hb91bd55_5

clangxxosx:
  - 11.0.0 h7e1b574_5

clang:
  - 11.0.0 h694c41f_2

llvmopenmp:
  - 11.0.0 h73239a0_1

osxfortran:
  - 7.3.0 h22b1bf0_7

libcxx:
  - 11.0.0 h4c3b8ed_1

gcc:
  - 9.3.0 h7247604_29

gxx:
  - 9.3.0 h0d07fa4_29

fortran:
  - 9.3.0 ha1c937c_29

gccimpl:
  - 9.3.0 h28f5a38_17

libblas:
  - 3.9.0 8_openblas

libcblas:
  - 3.9.0 8_openblas

liblapack:
  - 3.9.0 8_openblas

libopenblas:
  - 0.3.12 openmp_h63d9170_1

libglu:
  - 9.0.0 hf484d3e_1000

mesalib:
  - 18.3.1 h590aaf7_0

libpng:
  - 1.6.37 h7cec526_2          # [osx]
  - 1.6.37 hed695b0_2          # [linux]

# You simply _never_ change the following
mpi:
  - moose-mpich

pin_run_as_build:
  moose_mpich: x.x.x
  libblas: x.x.x
  libcblas: x.x.x
  liblapack: x.x.x
  moose_petsc: x.x.x
  moose_libmesh_vtk: x.x.x
  python: x.x

CONDA_BUILD_SYSROOT:           # [osx]
  - /opt/MacOSX10.9.sdk        # [osx]

macos_min_version:             # [osx]
  - 10.9                       # [osx]

macos_machine:                 # [osx]
  - x86_64-apple-darwin13.4.0  # [osx]

MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 10.9                       # [osx]
