moose_libgfortran:
  - libgfortran-ng 13.1.0 h69a702a_0                        # [linux]
  - libgfortran 5.0.0 11_3_0_h97931a8_31                    # [not arm64 and osx]
  - libgfortran 5.0.0 12_2_0_hd922786_31                    # [arm64]

moose_libgfortran5:
  - libgfortran5 13.1.0 h15d22d2_0                          # [linux]
  - libgfortran5 12.2.0 he409387_31                         # [not arm64 and osx]
  - libgfortran5 12.2.0 h0eea778_31                         # [arm64]

moose_ld64:                                                 # [osx]
  - ld64 609                                                # [not arm64 and osx]
  - ld64_osx-arm64 609                                      # [arm64]

moose_hdf5:
  - hdf5 1.12.2 mpi_mpich_h5d83325_0                        # [linux]
  - hdf5 1.12.2 mpi_mpich_hc154f39_0                        # [not arm64 and osx]
  - hdf5 1.12.2 mpi_mpich_h16e63df_0                        # [arm64]

### Paraview (peacock) constraints/compatibility
moose_krb5:
  - krb5 1.20.1 h81ceb04_0                                  # [linux]
  - krb5 1.20.1 h049b76e_0                                  # [not arm64 and osx]
  - krb5 1.20.1 h69eda48_0                                  # [arm64]

moose_icu:                                                  # [linux]
  - icu 70.1                                                # [linux]

### End Paraview constraints

mpi:
  - moose-mpich

#### Support Libraries
moose_libxt:                                                # [linux]
  - libxt-devel-cos7-x86_64 1.1.5                           # [linux]

moose_libsm:                                                # [linux]
  - libsm-devel-cos7-x86_64 1.2.2                           # [linux]

moose_libx11:                                               # [linux]
  - libx11-devel-cos7-x86_64 1.6.7                          # [linux]

moose_libice:                                               # [linux]
  - libice-devel-cos7-x86_64 1.0.9                          # [linux]

moose_libxext:                                              # [linux]
  - libxext-devel-cos7-x86_64 1.3.3                         # [linux]

moose_mesa_libgl:                                           # [linux]
  - mesa-libgl-devel-cos7-x86_64 18.3.4                     # [linux]

moose_xorg_x11:                                             # [linux]
  - xorg-x11-proto-devel-cos7-x86_64 2018.4 h9b0a68f_1105   # [linux]

moose_libglu:                                               # [linux]
  - libglu 9.0.0                                            # [linux]

moose_mesalib:                                              # [linux]
  - mesalib 23.0.2                                          # [linux]

#### Darwin SDK SYSROOT
CONDA_BUILD_SYSROOT:                                        # [osx]
  - /opt/MacOSX10.12.sdk                                    # [not arm64 and osx]
  - /opt/MacOSX11.3.sdk                                     # [arm64]

macos_min_version:                                          # [osx]
  - 10.12                                                   # [not arm64 and osx]
  - 11.3                                                    # [arm64]

macos_machine:                                              # [osx]
  - x86_64-apple-darwin13.4.0                               # [not arm64 and osx]
  - arm64-apple-darwin20.0.0                                # [arm64]

MACOSX_DEPLOYMENT_TARGET:                                   # [osx]
  - 10.12                                                   # [not arm64 and osx]
  - 11.3                                                    # [arm64]
