## Dependencies are listed in descending order. Generally speaking any
## changes made will require additional changes to items listed above
## your change (except where otherwise noted)

# NCRC dependency
moose_tools:
  - moose-tools 2022.04.18

# NCRC default Python
moose_ncrc_python:
  - python 3.9

moose_libmesh:
  - moose-libmesh 2022.04.07 build_1

SHORT_VTK_NAME:
  - 9.1

vtk_version:
  - 9.1.0

moose_libmesh_vtk:
  - moose-libmesh-vtk 9.1.0

moose_petsc:
  - moose-petsc 3.16.5 build_3

moose_mpich:
  - moose-mpich 4.0.1 build_2

#### MOOSE_TOOLS stuff (order is important, must match python version order)
moose_python:
  - python 3.9
  - python 3.8
  - python 3.7                                             # [not arm64]

moose_numpy:
  - numpy 1.22.1 py39h9d9ce41_0                            # [not arm64 and osx]
  - numpy 1.22.1 py38h9d72dae_0                            # [not arm64 and osx]
  - numpy 1.21.5 py37h3c8089f_0                            # [not arm64 and osx]
  - numpy 1.21.1 py39hdbf815f_0                            # [linux]
  - numpy 1.21.1 py38h9894fe3_0                            # [linux]
  - numpy 1.21.1 py37h038b26d_0                            # [linux]
  - numpy 1.21.3 py39h1f3b974_0                            # [arm64]
  - numpy 1.21.3 py38hbf7bb01_0                            # [arm64]

moose_pyqt:                                                # [not arm64]
  - pyqt 5.12.3 py39h6e9494a_8                             # [not arm64 and osx]
  - pyqt 5.12.3 py38h50d1736_8                             # [not arm64 and osx]
  - pyqt 5.12.3 py37hf985489_8                             # [not arm64 and osx]
  - pyqt 5.12.3 py39hf3d152e_7                             # [linux]
  - pyqt 5.12.3 py38h578d9bd_7                             # [linux]
  - pyqt 5.12.3 py37h89c1867_7                             # [linux]

moose_matplotlib:
  - matplotlib 3.5.1 py39h6e9494a_0                        # [not arm64 and osx]
  - matplotlib 3.5.1 py38h50d1736_0                        # [not arm64 and osx]
  - matplotlib 3.5.1 py37hf985489_0                        # [not arm64 and osx]
  - matplotlib 3.4.2 py39hf3d152e_0                        # [linux]
  - matplotlib 3.4.2 py38h578d9bd_0                        # [linux]
  - matplotlib 3.4.2 py37h89c1867_0                        # [linux]
  - matplotlib 3.4.3 py39hdf13c20_0                        # [arm64]
  - matplotlib 3.4.3 py38h150bfb4_0                        # [arm64]

moose_pandas:
  - pandas 1.4.0 py39h4d6be9b_0                             # [not arm64 and osx]
  - pandas 1.4.0 py38ha53d530_0                             # [not arm64 and osx]
  - pandas 1.3.5 py37h5b83a90_0                             # [not arm64 and osx]
  - pandas 1.3.1 py39hde0f152_0                             # [linux]
  - pandas 1.3.1 py38h1abd341_0                             # [linux]
  - pandas 1.3.1 py37h219a48f_0                             # [linux]
  - pandas 1.3.4 py39h7f752ed_0                             # [arm64]
  - pandas 1.3.4 py38h3777fb4_0                             # [arm64]

moose_pyyaml:
  - pyyaml 6.0 py39h89e85a6_3                               # [not arm64 and osx]
  - pyyaml 6.0 py38h96a0964_3                               # [not arm64 and osx]
  - pyyaml 6.0 py37h271585c_3                               # [not arm64 and osx]
  - pyyaml 5.4.1 py39h3811e60_0                             # [linux]
  - pyyaml 5.4.1 py38h497a2fe_0                             # [linux]
  - pyyaml 5.4.1 py37h5e8e339_0                             # [linux]
  - pyyaml 6.0 py39h5161555_0                               # [arm64]
  - pyyaml 6.0 py38hea4295b_0                               # [arm64]

moose_pybtex:
  - pybtex 0.24.0 pyhd8ed1ab_2                              # [not arm64 and osx]
  - pybtex 0.24.0 pyhd8ed1ab_2                              # [not arm64 and osx]
  - pybtex 0.24.0 pyhd8ed1ab_2                              # [not arm64 and osx]
  - pybtex 0.24.0 py39hf3d152e_0                            # [linux]
  - pybtex 0.24.0 py38h578d9bd_0                            # [linux]
  - pybtex 0.24.0 py37h89c1867_0                            # [linux]
  - pybtex 0.24.0 py39h2804cbe_0                            # [arm64]
  - pybtex 0.24.0 py38h10201cd_0                            # [arm64]

moose_mock:
  - mock 4.0.3 py39h6e9494a_2                               # [not arm64 and osx]
  - mock 4.0.3 py38h50d1736_2                               # [not arm64 and osx]
  - mock 4.0.3 py37hf985489_2                               # [not arm64 and osx]
  - mock 4.0.3 py39hf3d152e_1                               # [linux]
  - mock 4.0.3 py38h578d9bd_1                               # [linux]
  - mock 4.0.3 py37h89c1867_1                               # [linux]
  - mock 4.0.3 py39h2804cbe_1                               # [arm64]
  - mock 4.0.3 py38h10201cd_1                               # [arm64]

moose_lxml:
  - lxml 4.7.1 py39hf41e7f8_0                               # [not arm64 and osx]
  - lxml 4.7.1 py38h6ea4786_0                               # [not arm64 and osx]
  - lxml 4.6.3 py37h250624f_0                               # [not arm64 and osx]
  - lxml 4.6.3 py39h107f48f_0                               # [linux]
  - lxml 4.6.3 py38hf1fe3a4_0                               # [linux]
  - lxml 4.6.3 py37h77fd288_0                               # [linux]
  - lxml 4.6.3 py39h3757d6e_0                               # [arm64]
  - lxml 4.6.3 py38hd4105a3_0                               # [arm64]

moose_scikit_image:
  - scikit-image 0.19.1 py39h4d6be9b_0                      # [not arm64 and osx]
  - scikit-image 0.19.1 py38ha53d530_0                      # [not arm64 and osx]
  - scikit-image 0.19.1 py37h5b83a90_0                      # [not arm64 and osx]
  - scikit-image 0.18.2 py39hde0f152_0                      # [linux]
  - scikit-image 0.18.2 py38h1abd341_0                      # [linux]
  - scikit-image 0.18.2 py37h219a48f_0                      # [linux]
  - scikit-image 0.18.3 py39h7f752ed_0                      # [arm64]
  - scikit-image 0.18.3 py38h3777fb4_0                      # [arm64]

moose_sympy:
  - sympy 1.9 py39h6e9494a_1                                # [not arm64 and osx]
  - sympy 1.9 py38h50d1736_1                                # [not arm64 and osx]
  - sympy 1.9 py37hf985489_0                                # [not arm64 and osx]
  - sympy 1.9 py39hf3d152e_0                                # [linux]
  - sympy 1.9 py38h578d9bd_0                                # [linux]
  - sympy 1.9 py37h89c1867_0                                # [linux]
  - sympy 1.9 py39h2804cbe_0                                # [arm64]
  - sympy 1.9 py38h10201cd_0                                # [arm64]

moose_deepdiff:
  - deepdiff 5.5.0 pyhd8ed1ab_0

moose_beautifulsoup4:
  - beautifulsoup4 4.9.3 pyhb0f4dca_0

moose_pylatexenc:
  - pylatexenc 2.10 pyhd8ed1ab_0

moose_jinja2:
  - jinja2 3.0.1 pyhd8ed1ab_0

moose_mako:
  - mako 1.1.4 pyh44b312d_0

moose_livereload:
  - livereload 2.6.3 pyh9f0ad1d_0

moose_yaml:
  - yaml 0.2.5 h516909a_0                                   # [linux]
  - yaml 0.2.5 haf1e3a3_0                                   # [not arm64 and osx]
  - yaml 0.2.5 h642e427_0                                   # [arm64]

zip_keys:
  - moose_python
  - moose_numpy
  - moose_pyqt                                              # [not arm64]
  - moose_matplotlib
  - moose_pandas
  - moose_pyyaml
  - moose_pybtex
  - moose_mock
  - moose_lxml
  - moose_scikit_image
  - moose_sympy

#### Compilers
base_mpich:
  - mpich 4.0.1 h846660c_100                                # [linux]
  - mpich 4.0.1 hd33e60e_100                                # [not arm64 and osx]
  - mpich 4.0.1 hd4b5bf3_100                                # [arm64]

base_mpicc:
  - mpich-mpicc 4.0.1 hb600da9_100                          # [linux]
  - mpich-mpicc 4.0.1 h4fd26ce_100                          # [not arm64 and osx]
  - mpich-mpicc 4.0.1 haad7f49_100                          # [arm64]

base_mpicxx:
  - mpich-mpicxx 4.0.1 h166bdaf_100                         # [linux]
  - mpich-mpicxx 4.0.1 h5eb16cf_100                         # [not arm64 and osx]
  - mpich-mpicxx 4.0.1 h1c322ee_100                         # [arm64]

base_mpifort:
  - mpich-mpifort 4.0.1 h924138e_100                        # [linux]
  - mpich-mpifort 4.0.1 hbb4e6a2_100                        # [not arm64 and osx]
  - mpich-mpifort 4.0.1 h3e96240_100                        # [arm64]

moose_ld64:                                                 # [osx]
  - ld64 609 h4dfd969_10                                    # [not arm64 and osx]
  - ld64_osx-arm64 609 h7c97014_10                          # [arm64]

#### Support Libraries (libMesh and VTK)
moose_libglu:                                               # [linux]
  - libglu 9.0.0 hf484d3e_1000                              # [linux]

moose_mesalib:                                              # [linux]
  - mesalib 18.3.1 h590aaf7_0                               # [linux]

moose_libpng:                                               # [unix]
  - libpng 1.6.37 h7cec526_2                                # [not arm64 and osx]
  - libpng 1.6.37 hed695b0_2                                # [linux]
  - libpng 1.6.37 hf7e6567_2                                # [arm64]

moose_libxt:                                                # [linux]
  - libxt-devel-cos7-x86_64 1.1.5 h9b0a68f_1105             # [linux]

moose_libsm:                                                # [linux]
  - libsm-devel-cos7-x86_64 1.2.2 h9b0a68f_1105             # [linux]

moose_libx11:                                               # [linux]
  - libx11-devel-cos7-x86_64 1.6.7 h9b0a68f_1105            # [linux]

moose_libice:                                               # [linux]
  - libice-devel-cos7-x86_64 1.0.9 h9b0a68f_1105            # [linux]

moose_libxext:                                              # [linux]
  - libxext-devel-cos7-x86_64 1.3.3 h9b0a68f_1105           # [linux]

moose_mesa_libgl:                                           # [linux]
  - mesa-libgl-devel-cos7-x86_64 18.3.4 h9b0a68f_1105       # [linux]

moose_xorg_x11:                                             # [linux]
  - xorg-x11-proto-devel-cos7-x86_64 2018.4 h9b0a68f_1105   # [linux]

moose_hdf5:
  - hdf5 1.12.1 mpi_mpich_hfd824e9_4                        # [not arm64 and osx]
  - hdf5 1.12.1 mpi_mpich_h08b82f9_4                        # [linux]
  - hdf5 1.12.1 mpi_mpich_hfc22502_3                        # [arm64]

#### build/run pining
mpi:
  - moose-mpich

pin_run_as_build:
  moose_mpich: x.x.x
  moose_petsc: x.x.x
  moose_libmesh_vtk: x.x.x
  moose_python: x.x

#### Darwin SDK SYSROOT
CONDA_BUILD_SYSROOT:                                        # [osx]
  - /opt/MacOSX10.12.sdk                                    # [not arm64 and osx]
  - /opt/MacOSX11.3.sdk                                     # [arm64]

macos_min_version:                                          # [osx]
  - 10.12                                                   # [not arm64 and osx]
  - 11.3                                                    # [arm64]

macos_machine:                                              # [osx]
  - x86_64-apple-darwin13.4.0                               # [not arm64 and osx]
  - arm64-apple-darwin20.0.0                                # [arm64]

MACOSX_DEPLOYMENT_TARGET:                                   # [osx]
  - 10.12                                                   # [not arm64 and osx]
  - 11.3                                                    # [arm64]
