mpi:
  - mpich
  - openmpi

moose_mpi:
  - moose-mpi 2024.07.10

# Pesky packages that break internal CI
# Note: Modifying/Updating this will require changes to conda/mpich!
setuptools:
  - <60.0
pin_run_as_build:
  setuptools: x.x
