gcc: 12.2.1
clang: 16.0.6
minimum_gcc: 8.5.0
maximum_gcc: 12.2.1
minimum_clang: 10.0.1
maximum_clang: 16.0.6
python_default: 3.11
minimum_python: 3.9
maximum_python: 3.11
mpich: 4.2.1
openmpi: 4.1.6
petsc_alt: 3.11.4
petsc: 3.22.1.193.g72c1e49ee3d
apptainer_rockylinux: 8.8.20230518
apptainer_mpich: 3.4.3
apptainer_gcc: 12.2.1
default_mpi: mpich
python_packages: packaging pyaml jinja2
