Content:
    tutorial:
        root_dir: modules/subchannel/doc/tutorials

Executioner:
    type: MooseDocs.base.Serial

Renderer:
    type: MooseDocs.base.RevealRenderer
    theme: simple

Extensions:
    disable_defaults: True
    MooseDocs.extensions.reveal:
        translate: main/index.md
    MooseDocs.extensions.comment: default
    MooseDocs.extensions.command: default
    MooseDocs.extensions.core: default
    MooseDocs.extensions.config: default
    MooseDocs.extensions.media: default
    MooseDocs.extensions.floats: default
    MooseDocs.extensions.include: default
    MooseDocs.extensions.style: default
    MooseDocs.extensions.autolink: default
    MooseDocs.extensions.materialicon: default
    MooseDocs.extensions.heading: default
    MooseDocs.extensions.shortcut: default
    MooseDocs.extensions.table: default
    MooseDocs.extensions.layout: default
    MooseDocs.extensions.content: default
    MooseDocs.extensions.modal: default
    MooseDocs.extensions.listing: default
    MooseDocs.extensions.datetime: default
    MooseDocs.extensions.katex:
        macros: !include modules/doc/katex_macros.yml
