Content:
    - framework/doc/content
    - modules/shifted_boundary_method/doc/content
Renderer:
    type: MooseDocs.base.MaterializeRenderer
Extensions:
    MooseDocs.extensions.navigation:
        name: shifted_boundary_method
        repo: https://github.com/idaholab/moose
        home: /modules/shifted_boundary_method
    MooseDocs.extensions.appsyntax:
        executable: ${MOOSE_DIR}/modules/shifted_boundary_method
        remove: !include ${MOOSE_DIR}/framework/doc/remove.yml
        includes:
            - framework/include
            - modules/shifted_boundary_method/include
    MooseDocs.extensions.common:
        shortcuts: !include ${MOOSE_DIR}/framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms: !include ${MOOSE_DIR}/framework/doc/acronyms.yml
    MooseDocs.extensions.sqa:
        active: true
        reports: !include ${ROOT_DIR}/modules/shifted_boundary_method/doc/sqa_reports.yml
        categories:
            framework: !include ${MOOSE_DIR}/framework/doc/sqa_framework.yml
            shifted_boundary_method: !include ${ROOT_DIR}/modules/shifted_boundary_method/doc/sqa_shifted_boundary_method.yml
    MooseDocs.extensions.template:
        active: true
