mpi:
  - mpich
  - openmpi

moose_libmesh:
  - moose-libmesh 2025.05.23 mpich_1
  - moose-libmesh 2025.05.23 openmpi_1

moose_wasp:
  - moose-wasp 2025.05.13

moose_tools:
  - moose-tools 2025.06.13

zip_keys:
  - mpi
  - moose_libmesh
