mpi:
  - mpich
  - openmpi

moose_libmesh:
  - moose-libmesh 2025.11.25_c144a6e mpich_0
  - moose-libmesh 2025.11.25_c144a6e openmpi_0

moose_wasp:
  - moose-wasp 2025.09.19_02960f1

moose_tools:
  - moose-tools 2025.10.21

zip_keys:
  - mpi
  - moose_libmesh
