mpi:
  - mpich
  - openmpi

moose_libmesh:
  - moose-libmesh 2024.08.17 mpich_0
  - moose-libmesh 2024.08.17 openmpi_0

moose_wasp:
  - moose-wasp 2024.09.05

moose_tools:
  - moose-tools 2024.07.19

moose_peacock:
  - moose-peacock 2024.08.12

zip_keys:
  - mpi
  - moose_libmesh
