mpi:
  - mpich
  - openmpi

moose_libmesh:
  - moose-libmesh 2024.05.05 mpich_1
  - moose-libmesh 2024.05.05 openmpi_1

moose_wasp:
  - moose-wasp 2024.05.08

moose_tools:
  - moose-tools 2024.06.18

moose_peacock:
  - moose-peacock 2024.06.18

zip_keys:
  - mpi
  - moose_libmesh
