mpi:
  - mpich
  - openmpi

moose_libmesh:
  - moose-libmesh 2026.02.13_6232e98 mpich_1
  - moose-libmesh 2026.02.13_6232e98 openmpi_1

moose_wasp:
  - moose-wasp 2025.09.19_02960f1

moose_tools:
  - moose-tools 2026.02.16

zip_keys:
  - mpi
  - moose_libmesh
