mpi:
  - mpich
  - openmpi

moose_libmesh:
  - moose-libmesh 2025.10.15 mpich_0
  - moose-libmesh 2025.10.15 openmpi_0

moose_wasp:
  - moose-wasp 2025.09.18

moose_tools:
  - moose-tools 2025.10.21

zip_keys:
  - mpi
  - moose_libmesh
