mpi:
  - mpich
  - openmpi

moose_libmesh:
  - moose-libmesh 2024.12.02 mpich_0
  - moose-libmesh 2024.12.02 openmpi_0

moose_wasp:
  - moose-wasp 2024.11.13

moose_tools:
  - moose-tools 2024.11.13

moose_peacock:
  - moose-peacock 2024.11.13

zip_keys:
  - mpi
  - moose_libmesh
