mpi:
  - mpich
  - openmpi

moose_libmesh:
  - moose-libmesh 2024.10.17 mpich_0
  - moose-libmesh 2024.10.17 openmpi_0

moose_wasp:
  - moose-wasp 2024.05.08

moose_tools:
  - moose-tools 2024.10.01

moose_peacock:
  - moose-peacock 2024.10.01

zip_keys:
  - mpi
  - moose_libmesh
