name: Discussion Help Bot
on:
  discussion:
    types:
    # Use locked as trigger event until this chatbot is ready
      - created
    #  - locked
jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: MOOSE_discussion_bot

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run discuss bot
        run: python recommend_llamaIndex.py
        env:
          API_KEY: ${{ secrets.GITHUB_TOKEN }}
